apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: dev
spec:
 replicas: 2
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 25%
     maxSurge: 1      
 selectors:
   matchLabels:
     role: api
 template:
   metadata:
     labels:
       role: api
       env: dev
   spec:
     containers:
       - name: backend-container
         image: backend:100
         imagePullPolicy: Always
         env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
         ports:
        - containerPort: 3500
         livenessProbe:
          httpGet:
            path: /health
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
         readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
         startupProbe:
          httpGet:
            path: /started
            port: 3500
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30